/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_HW_MEM_GENERATED_TRACERS_H
#define TRACE_HW_MEM_GENERATED_TRACERS_H

#include "qemu-common.h"
#include "trace/control.h"

extern TraceEvent _TRACE_MHP_PC_DIMM_ASSIGNED_SLOT_EVENT;
extern TraceEvent _TRACE_MHP_PC_DIMM_ASSIGNED_ADDRESS_EVENT;
extern uint16_t _TRACE_MHP_PC_DIMM_ASSIGNED_SLOT_DSTATE;
extern uint16_t _TRACE_MHP_PC_DIMM_ASSIGNED_ADDRESS_DSTATE;
#define TRACE_MHP_PC_DIMM_ASSIGNED_SLOT_ENABLED 1
#define TRACE_MHP_PC_DIMM_ASSIGNED_ADDRESS_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_MHP_PC_DIMM_ASSIGNED_SLOT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_PC_DIMM_ASSIGNED_SLOT) || \
    false)

static inline void _nocheck__trace_mhp_pc_dimm_assigned_slot(int slot)
{
    if (trace_event_get_state(TRACE_MHP_PC_DIMM_ASSIGNED_SLOT) && qemu_loglevel_mask(LOG_TRACE)) {
        struct timeval _now;
        gettimeofday(&_now, NULL);
        qemu_log("%d@%zu.%06zu:mhp_pc_dimm_assigned_slot " "%d" "\n",
                 getpid(),
                 (size_t)_now.tv_sec, (size_t)_now.tv_usec
                 , slot);
    }
}

static inline void trace_mhp_pc_dimm_assigned_slot(int slot)
{
    if (true) {
        _nocheck__trace_mhp_pc_dimm_assigned_slot(slot);
    }
}

#define TRACE_MHP_PC_DIMM_ASSIGNED_ADDRESS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_PC_DIMM_ASSIGNED_ADDRESS) || \
    false)

static inline void _nocheck__trace_mhp_pc_dimm_assigned_address(uint64_t addr)
{
    if (trace_event_get_state(TRACE_MHP_PC_DIMM_ASSIGNED_ADDRESS) && qemu_loglevel_mask(LOG_TRACE)) {
        struct timeval _now;
        gettimeofday(&_now, NULL);
        qemu_log("%d@%zu.%06zu:mhp_pc_dimm_assigned_address " "0x%"PRIx64 "\n",
                 getpid(),
                 (size_t)_now.tv_sec, (size_t)_now.tv_usec
                 , addr);
    }
}

static inline void trace_mhp_pc_dimm_assigned_address(uint64_t addr)
{
    if (true) {
        _nocheck__trace_mhp_pc_dimm_assigned_address(addr);
    }
}
#endif /* TRACE_HW_MEM_GENERATED_TRACERS_H */
