xc_minios.o: xc_minios.c \
 ../../tools/config.h \
 /root/xen/stubdom/include/xen/memory.h xc_private.h _paths.h \
 include/xenctrl.h /root/xen/stubdom/include/xen/domctl.h \
 /root/xen/stubdom/include/xen/physdev.h \
 /root/xen/stubdom/include/xen/sysctl.h \
 /root/xen/stubdom/include/xen/version.h \
 /root/xen/stubdom/include/xen/hvm/dm_op.h \
 /root/xen/stubdom/include/xen/hvm/params.h \
 /root/xen/stubdom/include/xen/tmem.h \
 /root/xen/stubdom/include/xen/kexec.h \
 /root/xen/stubdom/include/xen/platform.h \
 ../../tools/libs/toollog/include/xentoollog.h \
 /root/xen/stubdom/include/xen/foreign/x86_32.h \
 /root/xen/stubdom/include/xen/foreign/x86_64.h \
 /root/xen/stubdom/include/xen/arch-x86/xen-mca.h \
 include/xenctrl_compat.h \
 ../../tools/libs/call/include/xencall.h \
 ../../tools/libs/foreignmemory/include/xenforeignmemory.h \
 ../../tools/libs/devicemodel/include/xendevicemodel.h \
 /root/xen/stubdom/include/xen/sys/privcmd.h \
 ../../tools/include/xen-tools/libs.h
